---
- name: reload systemd
  command: systemctl daemon-reload
  become: yes

- name: restart varnish
  service: name=varnish state=restarted
  become: yes

- name: apache-reload
  service: name=apache2 state=reloaded
  become: yes
