---
- name: Add PHP PPA
  apt_repository: repo='ppa:ondrej/php'
  become: yes
  ignore_errors: yes

- name: Creates default Apache html directory
  file: path=/var/www/html state=directory

- name: Force disable all PHP modules
  command: a2dismod {{ item }} removes=/etc/apache2/mods-enabled/{{ item }}.load
  with_items:
    - php5.6
    - php7.2
    - php7.4
    - php8.0
  become: yes
  notify: apache-restart

- name: Copy pre-compiled 5.6 Pecl extensions
  copy: src={{ item }} dest=/usr/lib/php/20131226  mode=755
  with_fileglob:
    - 20131226/*
  become: yes

- name: Copy pre-compiled 7.4 Pecl extensions
  copy: src={{ item }} dest=/usr/lib/php/20190902  mode=755
  with_fileglob:
    - 20190902/*
  become: yes

- name: Copy pre-compiled 8.0 Pecl extensions
  copy: src={{ item }} dest=/usr/lib/php/20200930  mode=755
  with_fileglob:
    - 20200930/*
  become: yes

- include_tasks: tasks/php/php5.6.yml
  when: params['php_version'] == 5.6

- include_tasks: tasks/php/php7.2.yml
  when: params['php_version'] == 7.2

- include_tasks: tasks/php/php7.4.yml
  when: params['php_version'] == 7.4

- include_tasks: tasks/php/php8.0.yml
  when: params['php_version'] == 8.0

- name: Install PHP & related packages
  apt:
    pkg:
      - php-xdebug
      - libgpgme11
      - libgpgme11-dev
      - libgpg-error-dev
      - libassuan-dev
      - php-pear
      - php-ssh2
      - libxml2-dev
    state: present
  become: yes

- name: Set propper PHP CLI versions
  alternatives:
    name: php
    path: "/usr/bin/php{{params['php_version']}}"
  become: yes

- name: Enable Apache's configured php version
  apache2_module:
    name: "{{ item.module}}"
    state: "{{ item.state}}"
    ignore_configcheck: true
    force: True
  with_items:
    - { module: "php{{ params['php_version'] }}", state: present}
  notify: apache-restart
  become: yes
  ignore_errors: yes

- name: Load Xdebug extension
  template: src=xdebug.ini.j2 dest=/etc/php/{{ item.phpversion }}/{{ item.sapi }}/20-xdebug.ini
  with_items:
    - { sapi: 'cli/conf.d', phpversion: "{{params['php_version']}}"}
    - { sapi: 'apache2/conf.d', phpversion: "{{params['php_version']}}"}
    - { sapi: 'mods-available', phpversion: "{{params['php_version']}}"}
  become: yes

- name: Disable Xdebug by default
  lineinfile:
    dest: "/etc/php/{{ item.phpversion }}/{{ item.sapi }}/20-xdebug.ini"
    regexp: '^zend_extension=xdebug'
    line: ';zend_extension=xdebug.so'
    backrefs: yes
  with_items:
    - { sapi: 'cli/conf.d', phpversion: "{{params['php_version']}}"}
    - { sapi: 'apache2/conf.d', phpversion: "{{params['php_version']}}"}
    - { sapi: 'mods-available', phpversion: "{{params['php_version']}}"}
  become: yes

- name: Add a ~/bin to PATH in Basch
  lineinfile: dest=~/.bashrc line='PATH="$HOME/bin:$PATH"'

- name: Make sure ~/bin exists
  file: path=~/bin state=directory

- name: Copy the php switcher script to ~/bin
  copy: src={{ item }} dest=~/bin/  mode=755
  with_fileglob:
    - bin/*

- name: Ensure symlinks for utilities exist
  file: src=~/bin/{{ item | basename | regex_replace('(\w+(?:\.\w+)*$)', '\1') }} dest=~/bin/{{ item | basename | regex_replace('\.sh','') }} mode=755 state=link force=true
  with_fileglob:
    - bin/*
