---
- name: Install PHP 7.4
  apt:
    pkg:
      - libapache2-mod-php7.4
      - php7.4-dev
      - php7.4-cli
      - php7.4-curl
      - php7.4-gd
      - php7.4-mysql
      - php7.4-mbstring
      - php7.4-simplexml
      - php7.4-xml
      - php7.4-zip
      - php7.4-apcu
      - php7.4-sqlite3
      - php7.4-intl
      - php7.4-soap
      - php7.4-imap
      - php7.4-bcmath
      - php7.4-tidy
      - php7.4-bz2
      - php7.4-soap
      - php7.4-gmp
    state: present
  become: yes
