---
- name: Install PHP 7.2
  apt:
    pkg:
      - libapache2-mod-php7.2
      - php7.2-dev
      - php7.2-cli
      - php7.2-curl
      - php7.2-gd
      - php7.2-mysql
      - php7.2-mbstring
      - php7.2-simplexml
      - php7.2-xml
      - php7.2-zip
      - php7.2-apcu
      - php7.2-sqlite3
      - php7.2-intl
      - php7.2-soap
      - php7.2-imap
      - php7.2-bcmath
      - php7.2-tidy
      - php7.2-bz2
      - php7.2-soap
      - php7.2-gmp
    state: present
  become: yes

- name: Remove deprecated extensions for PHP 7.2
  apt:
    pkg:
      - php7.2-mcrypt
      - php7.2-libsodium
    state: absent
  become: yes

- name: Remove libsodium extension
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/php/7.2/apache2/conf.d/20-libsodium.ini
    - /etc/php/7.2/cli/conf.d/20-libsodium.ini
    - /usr/lib/php/20170718/libsodium.so
  become: yes

- name: Install Required PHP Dependencies to Install Mcrypt
  apt:
    pkg:
      - php7.2-dev
      - php-pear
      - libmcrypt-dev
    state: present
  become: yes

- name: Load mcrypt extension
  template: src=mcrypt.ini dest=/etc/php/{{ item.phpversion }}/{{ item.sapi }}/mcrypt.ini
  with_items:
    - { sapi: 'cli/conf.d', phpversion: "{{params['php_version']}}"}
    - { sapi: 'apache2/conf.d', phpversion: "{{params['php_version']}}"}
    - { sapi: 'mods-available', phpversion: "{{params['php_version']}}"}
  become: yes

- name: Enable mcrypt extension
  lineinfile:
    dest: "/etc/php/{{ item.phpversion }}/{{ item.sapi }}/mcrypt.ini"
    regexp: ';extension=mcrypt.so'
    line: 'extension=mcrypt.so'
    backrefs: yes
  with_items:
    - { sapi: 'cli/conf.d', phpversion: "{{params['php_version']}}"}
    - { sapi: 'apache2/conf.d', phpversion: "{{params['php_version']}}"}
    - { sapi: 'mods-available', phpversion: "{{params['php_version']}}"}
  become: yes
