---
- name: Install PHP 7.2
  apt:
    pkg:
      - libapache2-mod-php7.2
      - php7.2-apcu
      - php7.2-bcmath
      - php7.2-bz2
      - php7.2-cli
      - php7.2-curl
      - php7.2-dev
      - php7.2-gmp
      - php7.2-gd
      - php7.2-imap
      - php7.2-intl
      - php7.2-mysql
      - php7.2-mbstring
      - php7.2-simplexml
      - php7.2-sqlite3
      - php7.2-soap
      - php7.2-tidy
      - php7.2-xml
      - php7.2-zip
    state: present
  become: yes

#- name: Copy pre-compiled 7.2 Pecl extensions
#  copy: src={{ item }} dest=/usr/lib/php/20200930  mode=755
#  with_fileglob:
#    - 20170718/*
#  become: yes

#- name: Add mcrypt extension
#  template: src=mcrypt.ini.j2 dest=/etc/php/7.2/{{ item.sapi }}/20-mcrypt.ini
#  with_items:
#    - { sapi: 'cli/conf.d' }
#    - { sapi: 'apache2/conf.d' }
#    - { sapi: 'mods-available' }
#  become: yes
