---
- name: Install PHP 8.0
  apt:
    pkg:
      - php8.0
      - libapache2-mod-php8.0
    state: present
  notify: apache-restart
  become: yes

- name: Install Php-FPM; a FastCGI process manager for PHP
  apt:
    pkg:
      - php8.0-fpm
      - libapache2-mod-fcgid
    state: present
  notify: apache-restart
  become: yes

- name: Disable PHP-FPM modules to avoid errors
  apache2_module:
    state: absent
    name: "{{ item.module}}"
    identifier: "{{ item.identifier}}"
    force: true
  with_items:
    - { module: "proxy_fcgi", identifier: proxy_fcgi_module}
    - { module: "setenvif", identifier: setenvif_module}
  notify: apache-restart
  become: yes

- name: Enable PHP-FPM as it is not enabled in Apache by default.
  apache2_module:
    name: "{{ item.module}}"
    identifier: "{{ item.identifier}}"
    state: present
    ignore_configcheck: true
    force: true
  with_items:
    - { module: "proxy_fcgi", identifier: proxy_fcgi_module}
    - { module: "setenvif", identifier: setenvif_module}
  notify: apache-restart
  become: yes

- name: Install PHP 8.0 extensions
  apt:
    pkg:
      - php8.0-amqp
      - php8.0-apcu
      - php8.0-bcmath
      - php8.0-bz2
      - php8.0-cli
      - php8.0-curl
      - php8.0-dev # for compiling other extensions like xdebug
      - php8.0-gd
      - php8.0-gmp
      - php8.0-imap
      - php8.0-intl
      - php8.0-ldap
      - php8.0-mbstring
      - php8.0-mysql
      - php8.0-pcov
      - php8.0-redis
      - php8.0-simplexml
      - php8.0-soap
      - php8.0-sqlite3
      - php8.0-tidy
      - php8.0-xml
      - php8.0-zip
    state: present
  notify: apache-restart
  become: yes
