---
- name: Install PHP 8.0
  apt:
    pkg:
      - libapache2-mod-php8.0
      - php8.0-dev
      - php8.0-fpm
      - libapache2-mod-fcgid
      - php8.0-cli
      - php8.0-curl
      - php8.0-gd
      - php8.0-mysql
      - php8.0-mbstring
      - php8.0-simplexml
      - php8.0-xml
      - php8.0-zip
      - php8.0-apcu
      - php8.0-sqlite3
      - php8.0-intl
      - php8.0-soap
      - php8.0-imap
      - php8.0-bcmath
      - php8.0-tidy
      - php8.0-bz2
      - php8.0-soap
      - php8.0-gmp
      - php-pear
    state: present
  become: yes

- name:  Enable PHP-FPM as it is not enabled in Apache by default.
  apache2_module:
    name: "{{ item.module}}"
    state: "{{ item.state}}"
    ignore_configcheck: true
  with_items:
    - { module: "proxy_fcgi", state: present}
    - { module: "setenvif", state: present}
  notify: apache-restart
  become: yes

- name: Enabling conf
  command: >
    a2enconf {{ item }}
  args:
    creates: "/etc/apache2/conf-enabled/{{ item }}.conf"
  when: item.state is not defined or item.state != 'absent'
  with_items:
    - php8.0-fpm
  notify: apache-restart
  become: yes
