#
- name: php - install xdebug support
  apt:
    name: ["php5.6-xdebug"]
    state: "present"
  when: "php_enable_xdebug|default(True)"
  become: yes

- name: php - set xdebug config
  template:
    src: "templates/xdebug.ini.j2"
    dest: "/etc/php/5.6/cli/conf.d/20-xdebug.ini"
    mode: 0644
    owner: "root"
    group: "root"
  when: "php_enable_xdebug|default(True)"
  become: yes
