---
- name: Configure the Yarn APT key
  apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg
  become: yes

- name: Add Yarn repository
  apt_repository:
    repo: 'deb https://dl.yarnpkg.com/debian/ stable main'
    state: present
  become: yes

- name: Install Yarn
  apt: pkg=yarn={{ yarn_version }} state=present
  become: yes
