# tasks file for mailcatcher
---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ mailcatcher_dependencies }}"
  tags:
    - mailcatcher-install-dependencies
  become: yes

- name: install mailcatcher (specific version)
  gem:
    name: mailcatcher
    version: "{{ mailcatcher_version }}"
    user_install: false
    executable: "/usr/bin/gem2.{{ mailcatcher_ruby_minor_version }}"
  when: "mailcatcher_version != 'latest'"
  tags:
    - mailcatcher-install-specific
  become: yes

- name: install mailcatcher (latest version)
  gem:
    name: mailcatcher
    state: "{{ mailcatcher_version }}"
    user_install: false
    executable: "/usr/bin/gem2.{{ mailcatcher_ruby_minor_version }}"
  when: "mailcatcher_version == 'latest'"
  tags:
    - mailcatcher-install-latest
  become: yes

- name: Ensures "/etc/php/*" directories exists
  file: path=/etc/php/{{ item.phpversion }}/apache2/conf.d/ state=directory
  with_items:
    - { phpversion: '5.6'}
    - { phpversion: '7.2'}
    - { phpversion: '7.4'}
    - { phpversion: '8.0'}
  become: yes

- name: Configure PHP's sendmail_path
  template: src={{ item.file }} dest=/etc/php/{{ item.phpversion }}/apache2/conf.d/{{ item.file }} force=yes owner=root group=root mode=0644
  with_items:
    - { file: 'mailcatcher.ini', phpversion: '5.6'}
    - { file: 'mailcatcher.ini', phpversion: '7.2'}
    - { file: 'mailcatcher.ini', phpversion: '7.4'}
    - { file: 'mailcatcher.ini', phpversion: '8.0'}
  become: yes
  notify:
    - apache-restart
