---
- name: MySQL => Install MySQL Server
  apt: pkg={{ item }} state=present
  notify: mysql-restart
  become: yes
  with_items:
    - python-mysqldb
    - mysql-server-5.7
    - mysql-client-core-5.7
    - mysql-client-5.7
    - libmysqlclient-dev

# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: MySQL => Update mysql root password for all root accounts
  mysql_user:
    name=root
    host={{ item }}
    password={{ mysql_root_password }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  become: yes

- name: MySQL => Copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  become: yes
