---
- name: MySQL => Install MySQL Server
  apt: pkg={{ item }} state=present
  notify: mysql-restart
  become: yes
  with_items:
    - python-mysqldb
    - mysql-server-5.7
    - mysql-client-core-5.7
    - mysql-client-5.7
    - libmysqlclient-dev
    - unixodbc-dev

# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: MySQL => Update mysql root password for all root accounts
  mysql_user:
    name=root
    host={{ item }}
    password={{ mysql_root_password }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  become: yes

- name: MySQL => Copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  become: yes

- name: Microsoft ODBC driver 18 => Copy bash file to ~/bin
  copy: src=templates/odbc.sh dest=~/bin/ mode=755

- name: Changing perm of "~/bin/odbc.sh", adding "+x"
  file:
    dest: ~/bin/odbc.sh
    mode: a+x

- name: Run Microsoft ODBC driver 18 install
  script: ~/bin/odbc.sh
  args:
    executable: bash
  become: yes
