---
# handlers file for ansible-mercure-rocks
- name: reload-systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: mercure-restart
  service:
    name: mercure.rocks
    state: restarted
  become: yes
