---
#The path where composer will be installed and available to your system. Should be in your user's $PATH so you can run commands simply with composer instead of the full path.
composer_path: /home/vagrant/bin/composer

# Set this to true to update Composer to the latest release every time the playbook is run.
composer_keep_updated: true

# You can install a specific release of Composer, e.g. composer_version: '1.0.0-alpha11'. If left empty the latest development version will be installed. Note that composer_keep_updated will override this variable, as it will always install the latest development version.
composer_version: ''

# You can choose which major branch of composer you wish to use. Default is --2. Note that composer_keep_updated will update the latest version available for this branch.
composer_version_branch: '--2'

# The COMPOSER_HOME path and directory ownership; this is the directory where global packages will be installed.
composer_home_path: '~/.composer'
composer_home_owner: vagrant
composer_home_group: vagrant

# A list of packages to install globally (using composer global require). If you want to install any packages globally, add a list item with a dictionary with the name of the package and a release, e.g. - { name: phpunit/phpunit, release: "4.7.*" }. The 'release' is optional, and defaults to @stable.
composer_global_packages: []
# - { name: phpunit/phpunit, release: "4.7.x" }
# - { name: phpunit/phpunit, release: "@stable" }

# If true, and if there are any configured composer_global_packages, the vendor/bin directory inside composer_home_path will be added to the system's default $PATH (for all users).
composer_add_to_path: false

# Add a project vendor/bin directory to the PATH
composer_add_project_to_path: false
# composer_project_path: /path/to/project/vendor/bin

# GitHub OAuth token, used to avoid GitHub API rate limiting errors when building and rebuilding applications using Composer. Follow GitHub's directions to Create a personal access (https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token) token if you run into these rate limit errors.
composer_github_oauth_token: ''
