---
# defaults file for ansible-mercure-rocks
mercure_rocks_user: mercure
mercure_rocks_addr: "127.0.0.1:3000"
mercure_rocks_compress: "true"
mercure_rocks_cors_allowed_origins: "*"
mercure_rocks_debug: "false"
mercure_rocks_demo: "false"
mercure_rocks_log_format: "TEXT"
mercure_rocks_transport_url: "null://"
mercure_rocks_jwt_key: "{{ params['mercure'].mercure_rocks_jwt_key }}"
mercure_rocks_jwt_algorithm: "HS256"
mercure_rocks_release: "{{ params['mercure'].mercure_rocks_release }}"
